### ISSUE TITLE
Bad encoding on export

### ISSUE THREAD

**Issue by jwise-mfg** [cesmii/ProfileDesigner#113]
Saving a Profile locally results in an Encoding that is not compatible with tools like [Prosys Forge](https://prosysopc.com/products/opc-ua-forge/). Changing the text encoding from UTF-8-BOM to UTF-8 would solve this issue.

**Comment by jwise-mfg** [comment]
Although the text in the XML claims UTF-8, examining the document with a tool like Notepad++ shows its not actually encoded that way.
![WrongEncoding](https://github.com/cesmii/ProfileDesigner/assets/57234292/8421af3c-be14-4b2d-83fd-28140189f896)

**Comment by scoxen1** [comment]
This appears to happen when trying to download a profile that the user has created within Profile Designer. A fix has been applied and is in stage site for testing. 

Note: When downloading a Cloud library profile, this does not appear to be a problem because that type of download is likely pulling the original XML file produced by Cloud Library. 
Note: I did confirm in notepad++ that the encoding is correct but did not test in Prosys Forge.

**Comment by scoxen1** [comment]
Deployed to live site. Marking done.
